
spring.application.name=Spring-jpa-job

spring.datasource.url=jdbc:mysql://localhost:3306/UserDetails
spring.datasource.username=root
spring.datasource.password=17AUGUST2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true